apiVersion: config.kubeflow.org/v1alpha2
kind: KfpControllerConfig
controller:
  health:
    healthProbeBindAddress: :8081
  metrics:
    bindAddress: :8080
  webhook:
    port: 9443
  leaderElection:
    leaderElect: true
    resourceName: kfp-operator-lock
spec:
  defaultBeamArgs:
    project: ${DATAFLOW_PROJECT}
  pipelineStorage: ${PIPELINE_STORAGE}
