resources:
- manager.yaml
- workflows/kfp/pipeline-steps.yaml
- workflows/kfp/create-pipeline.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-config
  files:
  - controller_manager_config.yaml
