apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-create-runconfiguration
spec:
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  arguments:
    parameters:
    - name: job-name
    - name: pipeline-name
    - name: pipeline-version
    - name: experiment-name
    - name: schedule
  templates:
  - name: main
    outputs:
      parameters:
      - name: job-id
        valueFrom:
          parameter: "{{`{{steps.create.outputs.result}}`}}"
    steps:
    - - name: create
        templateRef:
          name: runconfiguration-steps
          template: create
          clusterScope: true
        arguments:
          parameters:
          - name: job-name
            value: "{{`{{workflow.parameters.job-name}}`}}"
          - name: pipeline-name
            value: "{{`{{workflow.parameters.pipeline-name}}`}}"
          - name: pipeline-version
            value: "{{`{{workflow.parameters.pipeline-version}}`}}"
          - name: experiment-name
            value: "{{`{{workflow.parameters.experiment-name}}`}}"
          - name: schedule
            value: "{{`{{workflow.parameters.schedule}}`}}"
