apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-delete-experiment
spec:
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  arguments:
    parameters:
    - name: experiment-id
  templates:
  - name: main
    steps:
    - - name: delete
        templateRef:
          name: experiment-steps
          template: delete
          clusterScope: true
        arguments:
          parameters:
          - name: experiment-id
            value: '{{`{{workflow.parameters.experiment-id}}`}}'
