apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-delete-runconfiguration
spec:
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  arguments:
    parameters:
    - name: job-id
  templates:
  - name: main
    steps:
    - - name: delete
        templateRef:
          name: runconfiguration-steps
          template: delete
          clusterScope: true
        arguments:
          parameters:
          - name: job-id
            value: "{{`{{workflow.parameters.job-id}}`}}"
