apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-experiment-steps
spec:
  templates:
  - name: create
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        kfp-ext --endpoint '{{ .Values.manager.argo.kfpEndpoint }}' --output json experiment create '{{`{{inputs.parameters.experiment-name}}`}}' | jq -r '."ID"'
      image: kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
    inputs:
      parameters:
      - name: experiment-name
  - name: delete
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        echo y | kfp-ext --endpoint '{{ .Values.manager.argo.kfpEndpoint }}' --output json experiment delete '{{`{{inputs.parameters.experiment-id}}`}}'
      image: kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
    inputs:
      parameters:
      - name: experiment-id
