apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-pipeline-steps
spec:
  templates:
    - name: compile
      inputs:
        parameters:
        - name: compiler-config
        - name: pipeline-image
      outputs:
        artifacts:
        - name: pipeline
          path: /tmp/pipeline.yaml
      metadata:
        {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 8 }}
      container:
        command:
          - python3
        image: "{{`{{inputs.parameters.pipeline-image}}`}}"
        name: pipeline
        volumeMounts:
        - mountPath: /shared
          name: shared
        args:
        - /shared/compile.py
        - --output_file
        - /tmp/pipeline.yaml
        - --pipeline_config
        - |
          {{`{{inputs.parameters.compiler-config}}`}}
        {{ .Values.manager.argo.containerDefaults | toYaml | nindent 8 }}
      volumes:
      - name: shared
      initContainers:
      - args:
        - /shared
        image: {{ include "kfp-operator.trimmedContainerRegistry" . }}kfp-operator-argo-kfp-compiler:{{ .Chart.AppVersion }}
        mirrorVolumeMounts: true
        name: compile
        {{ .Values.manager.argo.containerDefaults | toYaml | nindent 8 }}
    - name: upload
      inputs:
          artifacts:
          - name: pipeline
            path: /tmp/pipeline.yaml
          parameters:
          - name: pipeline-name
      metadata:
        {{- .Values.manager.argo.metadataDefaults | toYaml | nindent 8 }}
      script:
        command:
        - ash
        image: {{ .Values.containerRegistry }}kfp-operator-argo-kfp-sdk:{{ .Chart.AppVersion }}
        source: |-
          set -e -o pipefail
          kfp-ext --endpoint '{{ .Values.manager.argo.kfpEndpoint }}' --output json pipeline upload --pipeline-name '{{`{{inputs.parameters.pipeline-name}}`}}' '/tmp/pipeline.yaml' | jq -r '."Pipeline Details"."Pipeline ID"'
      {{ .Values.manager.argo.containerDefaults | toYaml | nindent 8 }}
    - name: update
      inputs:
        artifacts:
        - name: pipeline
          path: /tmp/pipeline.yaml
        parameters:
        - name: pipeline-id
        - name: pipeline-version
      metadata:
        {{ .Values.manager.argo.metadataDefaults | toYaml | nindent 8 }}
      script:
        command:
        - ash
        image: {{ .Values.containerRegistry }}kfp-operator-argo-kfp-sdk:{{ .Chart.AppVersion }}
        source: |-
          set -e -o pipefail
          kfp-ext --endpoint '{{ .Values.manager.argo.kfpEndpoint }}' --output json pipeline upload-version --pipeline-version '{{`{{inputs.parameters.pipeline-version}}`}}' --pipeline-id '{{`{{inputs.parameters.pipeline-id}}`}}' '/tmp/pipeline.yaml' | jq -r '."Version name"'
      {{ .Values.manager.argo.containerDefaults | toYaml | nindent 8 }}
