apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-runconfiguration-steps
spec:
  templates:
  - name: create
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        kfp-ext --endpoint '{{`{{workflow.parameters.kfp-endpoint}}`}}' --output json job submit --pipeline-name '{{`{{workflow.parameters.pipeline-name}}`}}' --job-name '{{`{{workflow.parameters.job-name}}`}}' --experiment-name '{{`{{workflow.parameters.experiment-name}}`}}' --version-name '{{`{{workflow.parameters.pipeline-version}}`}}' --cron-expression '{{`{{workflow.parameters.schedule}}`}}'  | jq -r '."Job Details"."ID"'
      image: {{ include "kfp-operator.trimmedContainerRegistry" . }}kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
  - name: delete
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        KFP_RESULT=$(kfp-ext --endpoint '{{`{{workflow.parameters.kfp-endpoint}}`}}' --output json job delete '{{`{{workflow.parameters.job-id}}`}}' 2>&1) || echo $KFP_RESULT | grep -o 'HTTP response body: {.*}' | cut -d ':' -f 2- | jq -e 'select(.code==5)'
      image: {{ include "kfp-operator.trimmedContainerRegistry" . }}kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-create-runconfiguration
spec:
  arguments:
    parameters:
    - name: job-name
    - name: pipeline-name
    - name: pipeline-version
    - name: experiment-name
    - name: schedule
    - name: kfp-endpoint
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: job-id
        valueFrom:
          parameter: '{{`{{steps.create.outputs.result}}`}}'
    steps:
    - - name: create
        templateRef:
          name: runconfiguration-steps
          template: create
          clusterScope: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-update-runconfiguration
spec:
  arguments:
    parameters:
    - name: job-id
    - name: job-name
    - name: pipeline-name
    - name: pipeline-version
    - name: experiment-name
    - name: schedule
    - name: kfp-endpoint
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    outputs:
      parameters:
      - name: job-id
        valueFrom:
          parameter: '{{`{{steps.create.outputs.result}}`}}'
    steps:
    - - name: delete
        templateRef:
          name: runconfiguration-steps
          template: delete
          clusterScope: true
    - - name: create
        templateRef:
          name: runconfiguration-steps
          template: create
          clusterScope: true
        continueOn:
          failed: true
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ include "kfp-operator.fullname" . }}-delete-runconfiguration
spec:
  arguments:
    parameters:
    - name: job-id
    - name: kfp-endpoint
  entrypoint: main
  {{ if .Values.manager.argo.serviceAccount -}}
  serviceAccountName: {{ .Values.manager.argo.serviceAccount }}
  {{- end }}
  templates:
  - name: main
    steps:
    - - name: delete
        templateRef:
          name: runconfiguration-steps
          template: delete
          clusterScope: true
