apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: create-pipeline
spec:
  templates:
  - name: main
    outputs:
      parameters:
      - name: pipeline-id
        valueFrom:
          parameter: "{{steps.upload.outputs.result}}"
      - name: pipeline-version
        valueFrom:
          parameter: "{{steps.update.outputs.result}}"
    steps:
    - - name: compile
        templateRef:
          name: pipeline-steps
          template: compile
          clusterScope: true
        arguments:
          parameters:
          - name: compiler-config
            value: "{{workflow.parameters.compiler-config}}"
          - name: pipeline-image
            value: "{{workflow.parameters.pipeline-image}}"
    - - name: upload
        templateRef:
          name: pipeline-steps
          template: upload
          clusterScope: true
        arguments:
          artifacts:
          - name: pipeline
            from: "{{steps.compile.outputs.artifacts.pipeline}}"
          parameters:
          - name: pipeline-name
            value: "{{workflow.parameters.pipeline-name}}"
    - - name: update
        templateRef:
          name: pipeline-steps
          template: update
          clusterScope: true
        arguments:
          artifacts:
          - name: pipeline
            from: "{{steps.compile.outputs.artifacts.pipeline}}"
          parameters:
          - name: pipeline-id
            value: "{{steps.upload.outputs.result}}"
          - name: pipeline-version
            value: "{{workflow.parameters.pipeline-version}}"
        continueOn:
          failed: true
  entrypoint: main
#  serviceAccountName: ${OPERATOR_SA}
  arguments:
    parameters:
    - name: compiler-config
    - name: pipeline-image
    - name: pipeline-name
    - name: pipeline-version
