apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: delete-runconfiguration
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: job-id
  templates:
  - name: main
    steps:
    - - name: delete
        templateRef:
          name: runconfiguration-steps
          template: delete
          clusterScope: true
        arguments:
          parameters:
          - name: job-id
            value: "{{workflow.parameters.job-id}}"
