apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: delete-pipeline
spec:
  templates:
  - name: main
    steps:
    - - name: delete
        templateRef:
          name: pipeline-steps
          template: delete
          clusterScope: true
        arguments:
          parameters:
          - name: pipeline-id
            value: "{{workflow.parameters.pipeline-id}}"
  entrypoint: main
  arguments:
    parameters:
    - name: pipeline-id
