apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: experiment-steps
spec:
  templates:
  - name: create
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        kfp-ext --endpoint '${KFP_ENDPOINT}' --output json experiment create '{{inputs.parameters.experiment-name}}' | jq -r '."ID"'
      image: kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
    inputs:
      parameters:
      - name: experiment-name
  - name: delete
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        echo y | kfp-ext --endpoint '${KFP_ENDPOINT}' --output json experiment delete '{{inputs.parameters.experiment-id}}'
      image: kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
    inputs:
      parameters:
      - name: experiment-id
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: create-experiment
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: experiment-name
  templates:
  - name: main
    outputs:
      parameters:
      - name: experiment-id
        valueFrom:
          parameter: "{{steps.create.outputs.result}}"
    steps:
    - - name: create
        templateRef:
          name: experiment-steps
          template: create
          clusterScope: true
        arguments:
          parameters:
          - name: experiment-name
            value: "{{workflow.parameters.experiment-name}}"
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: update-experiment
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: experiment-id
    - name: experiment-name
  templates:
  - name: main
    outputs:
      parameters:
      - name: experiment-id
        valueFrom:
          parameter: "{{steps.create.outputs.result}}"
    steps:
    - - name: delete
        templateRef:
          name: experiment-steps
          template: delete
          clusterScope: true
        arguments:
          parameters:
          - name: experiment-id
            value: "{{workflow.parameters.experiment-id}}"
    - - name: create
        continueOn:
          failed: true
        templateRef:
          name: experiment-steps
          template: create
          clusterScope: true
        arguments:
          parameters:
          - name: experiment-name
            value: "{{workflow.parameters.experiment-name}}"

---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: delete-experiment
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: experiment-id
  templates:
  - name: main
    steps:
    - - name: delete
        templateRef:
          name: experiment-steps
          template: delete
          clusterScope: true
        arguments:
          parameters:
          - name: experiment-id
            value: "{{workflow.parameters.experiment-id}}"
