apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: pipeline-steps
spec:
  templates:
  - name: compile
    inputs:
      parameters:
      - name: compiler-config
      - name: pipeline-image
    metadata: {}
    volumes:
    - name: shared
    container:
      name: pipeline
      image: "{{inputs.parameters.pipeline-image}}"
      imagePullPolicy: Never
      command:
      - python3
      args:
      - /shared/compile.py
      - --output_file
      - /tmp/pipeline.yaml
      - --pipeline_config
      - |
        {{inputs.parameters.compiler-config}}

      volumeMounts:
      - name: shared
        mountPath: /shared
    initContainers:
    - name: compile
      image: kfp-operator-argo-kfp-compiler:latest
      imagePullPolicy: Never
      mirrorVolumeMounts: true
      args:
      - /shared
    outputs:
      artifacts:
      - name: pipeline
        path: /tmp/pipeline.yaml
  - name: upload
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        kfp-ext --endpoint '${KFP_ENDPOINT}' --output json pipeline upload --pipeline-name '{{inputs.parameters.pipeline-name}}' '/tmp/pipeline.yaml' | jq -r '."Pipeline Details"."Pipeline ID"'
      image: kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
    inputs:
      artifacts:
      - name: pipeline
        path: /tmp/pipeline.yaml
      parameters:
      - name: pipeline-name
  - name: update
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        kfp-ext --endpoint '${KFP_ENDPOINT}' --output json pipeline upload-version --pipeline-version '{{inputs.parameters.pipeline-version}}' --pipeline-id '{{inputs.parameters.pipeline-id}}' '/tmp/pipeline.yaml' | jq -r '."Version name"'
      image: kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
    inputs:
      artifacts:
      - name: pipeline
        path: /tmp/pipeline.yaml
      parameters:
      - name: pipeline-id
      - name: pipeline-version
  - name: delete
    metadata: {}
    script:
      source: |-
        set -e -o pipefail
        kfp-ext --endpoint '${KFP_ENDPOINT}' --output json pipeline delete '{{inputs.parameters.pipeline-id}}'
      image: kfp-operator-argo-kfp-sdk:latest
      imagePullPolicy: Never
      command:
      - ash
    inputs:
      parameters:
      - name: pipeline-id
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: create-pipeline
spec:
  templates:
  - name: main
    outputs:
      parameters:
      - name: pipeline-id
        valueFrom:
          parameter: "{{steps.upload.outputs.result}}"
      - name: pipeline-version
        valueFrom:
          parameter: "{{steps.update.outputs.result}}"
    steps:
    - - name: compile
        templateRef:
          name: pipeline-steps
          template: compile
          clusterScope: true
        arguments:
          parameters:
          - name: compiler-config
            value: "{{workflow.parameters.compiler-config}}"
          - name: pipeline-image
            value: "{{workflow.parameters.pipeline-image}}"
    - - name: upload
        templateRef:
          name: pipeline-steps
          template: upload
          clusterScope: true
        arguments:
          artifacts:
          - name: pipeline
            from: "{{steps.compile.outputs.artifacts.pipeline}}"
          parameters:
          - name: pipeline-name
            value: "{{workflow.parameters.pipeline-name}}"
    - - name: update
        templateRef:
          name: pipeline-steps
          template: update
          clusterScope: true
        arguments:
          artifacts:
          - name: pipeline
            from: "{{steps.compile.outputs.artifacts.pipeline}}"
          parameters:
          - name: pipeline-id
            value: "{{steps.upload.outputs.result}}"
          - name: pipeline-version
            value: "{{workflow.parameters.pipeline-version}}"
        continueOn:
          failed: true
  entrypoint: main
  arguments:
    parameters:
    - name: compiler-config
    - name: pipeline-image
    - name: pipeline-name
    - name: pipeline-version
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: update-pipeline
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: compiler-config
    - name: pipeline-image
    - name: pipeline-id
    - name: pipeline-version
  templates:
  - name: main
    outputs:
      parameters:
      - name: pipeline-version
        valueFrom:
          parameter: "{{steps.update.outputs.result}}"
    steps:
    - - name: compile
        templateRef:
          name: pipeline-steps
          template: compile
          clusterScope: true
        arguments:
          parameters:
          - name: compiler-config
            value: "{{workflow.parameters.compiler-config}}"
          - name: pipeline-image
            value: "{{workflow.parameters.pipeline-image}}"
    - - name: update
        templateRef:
          name: pipeline-steps
          template: update
          clusterScope: true
        arguments:
          artifacts:
          - name: pipeline
            from: "{{steps.compile.outputs.artifacts.pipeline}}"
          parameters:
          - name: pipeline-id
            value: "{{workflow.parameters.pipeline-id}}"
          - name: pipeline-version
            value: "{{workflow.parameters.pipeline-version}}"
---
apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: delete-pipeline
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: pipeline-id
  templates:
  - name: main
    steps:
    - - name: delete
        templateRef:
          name: pipeline-steps
          template: delete
          clusterScope: true
        arguments:
          parameters:
          - name: pipeline-id
            value: "{{workflow.parameters.pipeline-id}}"
