apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: update-experiment
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: experiment-id
    - name: experiment-name
  outputs:
    parameters:
    - name: experiment-id
      valueFrom:
        parameter: "{{steps.create.outputs.result}}"
  templates:
  - name: main
    outputs:
      parameters:
      - name: experiment-id
        valueFrom:
          parameter: "{{steps.create.outputs.result}}"
    steps:
    - - name: delete
        templateRef:
          name: experiment-steps
          template: delete
          clusterScope: true
        arguments:
          parameters:
          - name: experiment-id
            value: "{{workflow.parameters.experiment-id}}"
    - - name: create
        continueOn:
          failed: true
        templateRef:
          name: experiment-steps
          template: create
          clusterScope: true
        arguments:
          parameters:
          - name: experiment-name
            value: "{{workflow.parameters.experiment-name}}"
